name: flake8

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: test path
      run: |
        PYTHONPATH=./src pytest -cov=src tests/ --cov-report=html
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: rapport test2
        path: rapport/rapport.txt
    - name: Analysing the code with pylint
      run: |
        flake8 $(git ls-files '*.py')
    
    
